@startuml
'https://plantuml.com/class-diagram


class FlyweightFactory {
- pool
+ getFlyweight(char charname)
}

class Flyweight {
+ methodA
+ methodB
}

class Client {
}

Client -up--> FlyweightFactory :: Uses
Client -up--> Flyweight :: Uses
FlyweightFactory o--> Flyweight :: Creates

@enduml