/* javah -jni JNITest 命令生成：JNITest.h 头文件 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"   /* 把<jni.h>改成"jni.h" */
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    testN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_testN
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
